import * as fs from 'fs';
import * as path from 'path';

import { config } from '../config';
import { AiAgentRunParsedFields, AiAgentRunQaCheck } from '../db/types';
import { ensurePr } from '../git/pr';
import { commitAll, pushBranch } from '../git/repo';

export interface FinalizeResult {
  finalHandoffContent: string;
  thumbnailPromptContent: string;
  adminPayloadContent: string;
  backendPrUrl: string;
  frontendPrUrl: string;
}

interface GamesJsonEntry {
  gameId: string;
  gameName: string;
  description: string;
  minBet: number;
  maxBet: number;
  isActive: boolean;
  freebetEnabled: boolean;
  category: string;
}

function appendToGamesJson(parsedFields: AiAgentRunParsedFields): void {
  const gamesJsonPath = path.join(config.gameBackendPath, 'docs', 'games.json');
  const games = JSON.parse(fs.readFileSync(gamesJsonPath, 'utf8')) as GamesJsonEntry[];
  if (games.some((g) => g.gameId === parsedFields.gameId)) return;
  games.push({
    gameId: parsedFields.gameId,
    gameName: parsedFields.gameName,
    description: parsedFields.description,
    minBet: parsedFields.minBet,
    maxBet: parsedFields.maxBet,
    isActive: true,
    freebetEnabled: parsedFields.freebetEnabled,
    category: parsedFields.category,
  });
  fs.writeFileSync(gamesJsonPath, `${JSON.stringify(games, null, 2)}\n`, 'utf8');
}

function buildThumbnailPrompt(parsedFields: AiAgentRunParsedFields): string {
  return `# Thumbnail prompt — ${parsedFields.gameName}

A vibrant, polished 1:1 square casino-app game icon for "${parsedFields.gameName}" (${parsedFields.archetype} archetype, ${parsedFields.category} category). ${parsedFields.description}

Style: match the house's existing game icon set — bold saturated colors, high-contrast central subject, subtle glossy/neon highlights, no text or UI chrome baked into the image, a clean silhouette readable at small sizes (e.g. a sidebar thumbnail). Composition: the game's core visual motif centered, dramatic lighting, casino/gambling aesthetic — thematic props appropriate to the game's own theme, not generic cards/dice unless the game itself is card/dice-based.

Generate the actual image with your own image-generation tool, then place it at \`public/thumbnails/${parsedFields.gameId}.<ext>\` in game-frontend and wire it via the backend's \`thumbnail\` field on \`IGameConfig\`.
`;
}

function buildAdminPayload(parsedFields: AiAgentRunParsedFields): string {
  const body: GamesJsonEntry = {
    gameId: parsedFields.gameId,
    gameName: parsedFields.gameName,
    description: parsedFields.description,
    minBet: parsedFields.minBet,
    maxBet: parsedFields.maxBet,
    isActive: true,
    freebetEnabled: parsedFields.freebetEnabled,
    category: parsedFields.category,
  };
  return `# Admin payload — ${parsedFields.gameName}

Run these once both PRs are merged and deployed, to make the game live without a redeploy.

\`\`\`bash
curl -X POST "\${ADMIN_BASE_URL}/gambling/games" \\
  -H "x-admin-api-key: \${ADMIN_API_KEY}" \\
  -H "Content-Type: application/json" \\
  -d '${JSON.stringify(body)}'

curl -X POST "\${ADMIN_BASE_URL}/gambling/games/refresh-configs" \\
  -H "x-admin-api-key: \${ADMIN_API_KEY}"
\`\`\`
`;
}

function buildFinalHandoff(
  parsedFields: AiAgentRunParsedFields,
  specDocContent: string,
  qaChecks: AiAgentRunQaCheck[],
  qaSummary: string,
): string {
  const qaTable = qaChecks
    .map((c) => `| ${c.check} | ${c.pass ? 'PASS' : 'FAIL'} | ${c.measured ?? ''} | ${c.expected ?? ''} |`)
    .join('\n');
  return `# Handoff — ${parsedFields.gameName}

Built by the Gemini AI-agent pipeline (\`cherry_agents\`) — a separate pipeline from the Claude-Code-driven \`/create-game\` command.

## QA result

${qaSummary}

| Check | Result | Measured | Expected |
|---|---|---|---|
${qaTable}

## Spec

${specDocContent}
`;
}

/**
 * Deterministic — no Gemini call. games.json + handoff docs are template-filled from
 * parsedFields/specDocContent/qaChecks, not generated by a model, mirroring create-game.md's
 * step 8 ("Finalize (do this yourself, no subagent)").
 */
export async function runFinalizePhase(
  parsedFields: AiAgentRunParsedFields,
  specDocContent: string,
  qaChecks: AiAgentRunQaCheck[],
  qaSummary: string,
  backendBranch: string,
  frontendBranch: string,
): Promise<FinalizeResult> {
  appendToGamesJson(parsedFields);

  const handoffsDir = path.join(config.gameBackendPath, 'docs', 'ai-agent-handoffs');
  fs.mkdirSync(handoffsDir, { recursive: true });

  const finalHandoffContent = buildFinalHandoff(parsedFields, specDocContent, qaChecks, qaSummary);
  const thumbnailPromptContent = buildThumbnailPrompt(parsedFields);
  const adminPayloadContent = buildAdminPayload(parsedFields);

  fs.writeFileSync(path.join(handoffsDir, `HANDOFF_${parsedFields.fileSlug}.md`), finalHandoffContent, 'utf8');
  fs.writeFileSync(path.join(handoffsDir, `HANDOFF_${parsedFields.fileSlug}_THUMBNAIL_PROMPT.md`), thumbnailPromptContent, 'utf8');
  fs.writeFileSync(path.join(handoffsDir, `HANDOFF_${parsedFields.fileSlug}_ADMIN_PAYLOAD.md`), adminPayloadContent, 'utf8');

  // Conventional Commits, lowercase type + subject — game_backend's commit-msg hook
  // (commitlint, @commitlint/config-conventional) rejects anything else.
  await commitAll(config.gameBackendPath, `feat: add ${parsedFields.gameId} to games.json + handoff docs`);
  await pushBranch(config.gameBackendPath, backendBranch);
  await pushBranch(config.gameFrontendPath, frontendBranch);

  const prTitle = `Add game: ${parsedFields.gameName}`;
  const prBody = `AI-agent generated game (Gemini pipeline, \`cherry_agents\`).\n\nRTP target: ${parsedFields.rtpTarget}%\nQA: ${qaSummary}\n\nSee \`docs/ai-agent-handoffs/HANDOFF_${parsedFields.fileSlug}.md\` for full detail.`;

  const backendPrUrl = await ensurePr(config.gameBackendPath, backendBranch, 'dev', prTitle, prBody);
  const frontendPrUrl = await ensurePr(config.gameFrontendPath, frontendBranch, 'dev', prTitle, prBody);

  return { finalHandoffContent, thumbnailPromptContent, adminPayloadContent, backendPrUrl, frontendPrUrl };
}
