import * as fs from 'fs';
import * as path from 'path';
import { config } from '../config';
import { GameSpec } from '../agents/game-designer.agent';

export class DbCatalogSeederTool {
  /**
   * Generates a PostgreSQL seed script to register the new game into webapp.games table
   */
  static seedGameCatalog(spec: GameSpec): string {
    const timestamp = Date.now();
    const migrationFilename = `${timestamp}-add-${spec.gameId}-game.sql`;

    const baseDir = config.paths.backend || path.resolve(__dirname, '../../game_backend');
    const migrationsDir = path.join(baseDir, 'migrations');

    if (!fs.existsSync(migrationsDir)) {
      fs.mkdirSync(migrationsDir, { recursive: true });
    }

    const migrationPath = path.join(migrationsDir, migrationFilename);

    const sqlContent = `-- Auto-generated by Cherry Genesis AI Agent on ${new Date().toISOString()}
-- Game: ${spec.gameTitle} (${spec.gameTitleRu})

INSERT INTO webapp.games (
  "gameId",
  "gameName",
  "image",
  "thumbnail",
  "category",
  "provider",
  "hasFreespin",
  "tags",
  "priority",
  "deleted",
  "createdAt",
  "updatedAt"
)
VALUES (
  '${spec.gameId}',
  '${spec.gameTitle.replace(/'/g, "''")}',
  '/games/${spec.gameId}/assets/bg.png',
  '/games/${spec.gameId}/assets/hero.png',
  '${spec.gameType}',
  'Cherry Genesis AI',
  false,
  '["AI", "Provably Fair", "Web3", "${spec.theme.replace(/'/g, "''")}"]'::jsonb,
  100,
  0,
  NOW(),
  NOW()
)
ON CONFLICT ("gameId") 
DO UPDATE SET 
  "gameName" = EXCLUDED."gameName",
  "thumbnail" = EXCLUDED."thumbnail",
  "image" = EXCLUDED."image",
  "updatedAt" = NOW();
`;

    fs.writeFileSync(migrationPath, sqlContent, 'utf-8');
    console.log(`🗄️ [DB Catalog Seeder] Created Postgres migration: ${migrationPath}`);
    return migrationPath;
  }
}
